version: '3.8'

services:
  # Servicio de la aplicaci√≥n Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sistemamedico?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - app-network
    restart: always

  # Servicio de la base de datos MySQL
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sistemamedico
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: